[package]
name = "hypervisor-cheat"
version = "0.1.0"
authors = ["main <main@user>"]
edition = "2018"

[dependencies]
vmread = { path = "../" }
vmread-sys = { features = ["kmod_rw"], path = "../vmread-sys" }
hexdump = "0.1.0"
memmem = "0.1.1"
sha2 = "0.9.1"
hex = "0.4.2"
bsdiff = "0.1.3"